PimWeb/HotelariaControle/HotelPim.Web/Controllers/HospedeController.cs
using HotelariaControle.Data.Models;
using HotelariaControle.Data.Servicos;
using HotelPim.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelPim.Web.Controllers
{
    public class HospedeController : Controller
    {
        private HospedeService oHospedeService = new HospedeService();

        public IActionResult Hospede()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Hospede(Hospedes model)
        {
            if (ModelState.IsValid)
            {
                string dataNascimento = Request.Form["nascimento"];

                model.DataDeNascimento = Convert.ToDateTime(dataNascimento);

                model.HStatus = Convert.ToBoolean(1);

                string NomeHospede = Request.Form["nome"];

                TempData["NomeHospede"] = NomeHospede;

                oHospedeService.oRepositoryHospede.Incluir(model);

                return RedirectToAction("Create", "Usuario");
            }

            return View();


        }
    }
}

PimWeb/HotelariaControle/HotelPim.Web/Views/Shared/_Layout.cshtml
@model ReservaViewModel

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelPim.Web</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" media="(max-width: 600px)" href="~/css/style600.css" />
</head>
<body>
    <!-- HEADER -->
    <header>

        <!-- MENU -->
        <nav>
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Reserva">Quartos</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a></li>
                <li>
                    <a asp-area="" asp-controller="Usuario" asp-action="Login" class="login">Login</a>
                    <a asp-area="" asp-controller="Hospede" asp-action="Hospede" class="ocultar"> / Cadastro</a>
                </li>
            </ul>
        </nav>
            <!-- CONSULTA -->
        <div class="consulta">
            <form asp-action="ReservarQuarto">
                <!-- OPCAO HOTEL -->
                <div class="hotel">
                    <div class="titulo">
                        <p>Hoteis</p>
                    </div>
                    <div class="select">
                        <div class="icone">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" />
                            </svg>
                        </div>
                        <label asp-for="oQuartos">
                            <select asp-for="oQuartos" name="lista" id="lista"
                                    asp-items="@(new SelectList(ViewBag.ListaDeQuartos, "Value", "Text"))">
                            </select>
                        </label>
                    </div>
                </div>
                <!-- OPCAO DATA -->
                <div class="data">
                    <div class="titulo">
                        <p>Datas</p>
                    </div>
                    <div class="input">
                        <label asp-for="oReserva.CheckIn">
                            <input asp-for="oReserva.CheckIn" type="date" name="dataCheckIn" />
                            <span asp-validation-for="oReserva.CheckIn" class="text-danger"></span>
                        </label>
                        <label asp-for="oReserva.CheckOut">
                            <input asp-for="oReserva.CheckOut" type="date" name="dataCheckOut" />
                            <span asp-validation-for="oReserva.CheckOut" class="text-danger"></span>
                        </label>
                    </div>
                </div>
                <!-- OPCAO ADULTOS -->
                <div class="adultos">
                    <div class="titulo">
                        <p>Adultos</p>
                    </div>
                    <div class="select">
                        <div class="icone">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                            </svg>
                        </div>
                        <select name="select">
                            <option value="1">1 Adulto</option>
                            <option value="2" selected>2 Adultos</option>
                            <option value="3">3 Adultos</option>
                            <option value="4">4 Adultos</option>
                            <option value="5">5 Adultos</option>
                            <option value="6">6 Adultos</option>
                            <option value="7">7 Adultos</option>
                            <option value="8">8 Adultos</option>
                            <option value="9">9 Adultos</option>
                            <option value="10">10 Adultos</option>
                        </select>
                    </div>
                </div>
                <!-- OPCAO CRIANCAS -->
                <div class="criancas">
                    <div class="titulo">
                        <p>Crianças</p>
                    </div>
                    <div class="select">
                        <div class="icone">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z" />
                                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
                            </svg>
                        </div>
                        <select name="select">
                            <option value="1" selected>0 Criança</option>
                            <option value="1">1 Criança</option>
                            <option value="2">2 Crianças</option>
                            <option value="3">3 Crianças</option>
                            <option value="4">4 Crianças</option>
                            <option value="5">5 Crianças</option>
                            <option value="6">6 Crianças</option>
                            <option value="7">7 Crianças</option>
                            <option value="8">8 Crianças</option>
                            <option value="9">9 Crianças</option>
                            <option value="10">10 Crianças</option>
                        </select>
                    </div>
                </div>
                <!-- botao -->
                <div class="botao">
                    <input type="submit" value="Reservar" onclick="window.location = '@Url.Action("Index", "Home")'" />
                </div>
            </form>
        </div>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- FOOTER -->
    <footer>
        <div class="footer">
            <div class="logo">
                <img src="~/img/c1f2799e1f78fcd8c3597f4e0e05226f.png" alt="">
            </div>
            <div class="menu">
                <h2>Menu</h2>
                <nav>
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Reserva">Quartos</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a></li>
                    </ul>
                </nav>
            </div>
            <div class="projeto">
                <h2>Projeto</h2>
                <p>Neste projeto uma hotelaria de grande tradição decidiu contratar uma empresa para fazer o desenvolvimento do sistema para gerenciar seus hotéis. Após analisar os vários softwares existentes no mercado, decidiram contratar uma consultoria de informática especializada, a qual alocou a equipe da empresa “Project P” para o desenvolvimento do sistema interno de gerenciamento.</p>
            </div>
        </div>
        <div class="copy">
            <p>PIM IV - Desenvolvimento de um sistema de gestão hoteleira.</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>